### ISSUE TITLE
Can not initialize tokenizer

### ISSUE THREAD

**Issue by akirasosa** [laboroai/Laboro-DistilBERT-Japanese#1]
```python
from transformers import AutoTokenizer

sp_tokenizer = AutoTokenizer.from_pretrained('laboro-ai/distilbert-base-japanese')
```

It gets an error.
```
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

* Python 3.9.4
* Transformers 4.6.1

**Comment by mas-hama** [comment]
As we mentioned in README.md, this model requires AlbertTokenizer and it cannot be replaced by AutoTokenizer.

**Comment by akirasosa** [comment]
If I replace AutoTokenizer with AlbertTokenizer, tokenizer becomes None.

**Comment by mas-hama** [comment]
> If I replace AutoTokenizer with AlbertTokenizer, tokenizer becomes None.

I tried on my PC (MacOS Catalina 10.15.7) with Python 3.9.4 and Transformers 4.6.1, but it works correctly.

```
$ python
Python 3.9.4 (default, May 21 2021, 14:24:39) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from transformers import AlbertTokenizer
>>> sp_tokenizer = AlbertTokenizer.from_pretrained('laboro-ai/distilbert-base-japanese')
>>> sp_tokenizer
PreTrainedTokenizer(name_or_path='laboro-ai/distilbert-base-japanese', vocab_size=32000, model_max_len=1000000000000000019884624838656, is_fast=False, padding_side='right', special_tokens={'bos_token': '[CLS]', 'eos_token': '[SEP]', 'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'})
>>> import transformers
>>> transformers.__version__
'4.6.1'
>>> 
```

**Comment by xinyiz1019** [comment]
I tried with Transformers 4.6.1 and couldn't reproduce the error.
From the error message you got, maybe you want to double-check the path is correctly set.
And as mentioned by @mas-hama, please use AlbertTokenizer to get the expected tokenizer behavior.

**Comment by akirasosa** [comment]
Sorry! I restarted my console. Then, it works fine.
Thanks for your help.
